name: Upload Website

on:
  pull_request:
    branches:
    - main
    - develop
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: |
        if ${{ github.ref == 'refs/heads/main' }}; then
          aws s3 sync ./ s3://${{ secrets.PROD_BUCKET_NAME }} --exclude ".*" --exclude "README.md" --size-only --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.PROD_CDN_ID }} \
          --paths "/*"
        else
          aws s3 sync ./ s3://${{ secrets.DEV_BUCKET_NAME }} --exclude ".*" --exclude "README.md" --size-only --delete
        fi